#!/usr/bin/env bash
# Configures an Ubuntu server using the following configuration methed;
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

echo "127.0.0.2     localhost" > /etc/hosts
7 echo "8.8.8.8       facebook.com" >> /etc/hosts

 
