#!/usr/bin/bash

# Define variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f "$KEY_NAME" -N "$PASSPHRASE"

# Output success message
echo "RSA key pair successfully created."
echo "Private key: $KEY_NAME"
echo "Public key: $KEY_NAME.pub"

